# Generated by Django 5.0 on 2023-12-06 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mensalista',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50, verbose_name='Nome *')),
                ('cpf', models.CharField(max_length=11, verbose_name='CPF *')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Valor *')),
                ('data_inicial', models.DateField(verbose_name='Data de início *')),
                ('dia_vencimento', models.IntegerField(null=True, verbose_name='Dia de vencimetno *')),
                ('cep', models.CharField(max_length=9, verbose_name='CEP')),
                ('endereco', models.CharField(max_length=255, null=True, verbose_name='Endereço')),
                ('cidade', models.CharField(max_length=255, null=True, verbose_name='Cidade')),
                ('uf', models.CharField(max_length=2, null=True, verbose_name='UF')),
            ],
        ),
    ]
