# Generated by Django 5.0 on 2023-12-05 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mensalista',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50, verbose_name='Nome *')),
                ('cpf', models.CharField(max_length=11, verbose_name='CPF *')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Valor *')),
                ('data_inicial', models.DateField(verbose_name='Data de início *')),
                ('dia_vencimento', models.IntegerField(null=True, verbose_name='Dia de vencimetno *')),
                ('cep', models.IntegerField(null=True, verbose_name='CEP')),
                ('endereco', models.CharField(max_length=255, null=True, verbose_name='Endereço')),
                ('cidade', models.CharField(max_length=255, null=True, verbose_name='Cidade')),
                ('uf', models.CharField(max_length=2, null=True, verbose_name='UF')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('usuario', models.CharField(max_length=20, verbose_name='Usuário')),
                ('senha', models.CharField(max_length=20, verbose_name='Senha')),
            ],
        ),
    ]
