# Generated by Django 5.0 on 2023-12-05 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_estacionamento', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='usuario',
            field=models.CharField(max_length=20, unique=True, verbose_name='Usuário'),
        ),
    ]
