# Generated by Django 5.0 on 2023-12-07 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_estacionamento', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensalista',
            name='obs',
            field=models.TextField(blank=True, max_length=500, verbose_name='Observações'),
        ),
    ]
