# Generated by Django 5.0 on 2023-12-06 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_estacionamento', '0002_alter_usuario_usuario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
