# Generated by Django 5.0 on 2023-12-07 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_estacionamento', '0002_alter_mensalista_obs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensalista',
            name='dia_vencimento',
            field=models.IntegerField(verbose_name='Dia de vencimento *'),
        ),
    ]
