# Generated by Django 5.0 on 2023-12-07 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_estacionamento', '0002_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
