# Generated by Django 5.0 on 2023-12-08 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_estacionamento', '0004_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
