# Generated by Django 5.0 on 2023-12-18 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_estacionamento', '0005_delete_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensalista',
            name='situacao',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
    ]
