# Generated by Django 5.0 on 2023-12-18 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_estacionamento', '0006_mensalista_situacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensalista',
            name='situacao',
            field=models.BooleanField(blank=True, default=True, verbose_name='Ativo'),
        ),
    ]
