# Generated by Django 5.0 on 2024-01-17 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_estacionamento', '0007_alter_mensalista_situacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensalista',
            name='situacao',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
    ]
